import styles from "./about.module.scss";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div className={styles.container}>
      <h2>-About-</h2>
    </div>
  );
}
