import { Inter } from "next/font/google";

import "../styles/reset.css";
import "../styles/global.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <head />
      <body className={inter.className}>
        <div className="header">-Header-</div>
        {children}
        <div className="footer">-Footer-</div>
      </body>
    </html>
  );
}
